[workspace]
members = [
    "wallet-core",
    "dlc-core",
    "musig-core",
]
resolver = "2"

[workspace.dependencies]
wasm-bindgen = "0.2.100"
serde = { version = "1", features = ["derive"] }
serde_json = "1" 